name: Publish Release

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.BANNO_AUTOBOT_GITHUB_TOKEN }}

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v6
      with:
        token: ${{ env.GITHUB_TOKEN }}

    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: 21

    - uses: gradle/actions/setup-gradle@v6
      with:
        cache-provider: basic

    - id: previous_version
      run: |
        echo "previous-version=$(gh repo view --json latestRelease --jq '.latestRelease.tagName')" >> $GITHUB_OUTPUT

    - id: current_version
      uses: christian-draeger/read-properties@908f99d3334be3802ec7cb528395a69d19914e7b
      with:
        path: gordon-plugin/gradle.properties
        properties: version

    - name: Create Tag
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag -a ${{ steps.current_version.outputs.version }} -m ${{ steps.current_version.outputs.version }}
        git push origin ${{ steps.current_version.outputs.version }}

    - name: Create Release
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd
      with:
        tag: ${{ steps.current_version.outputs.version }}
        generateReleaseNotes: true
        generateReleaseNotesPreviousTag: ${{ steps.previous_version.outputs.previous-version }}
        makeLatest: true

    - name: Gradle Publish
      env:
        GRADLE_PLUGIN_PUBLISH_KEY: ${{ secrets.GRADLE_PLUGIN_PUBLISH_KEY }}
        GRADLE_PLUGIN_PUBLISH_SECRET: ${{ secrets.GRADLE_PLUGIN_PUBLISH_SECRET }}
      run: ./gradlew publishPlugins

    - id: next_version
      uses: christian-draeger/increment-semantic-version@4ac542a8ebf91f4edc224cbe3a19cc086826ae77
      with:
        current-version: ${{ steps.current_version.outputs.version }}
        version-fragment: bug

    - name: Bump Version
      uses: christian-draeger/write-properties@0c4fa75e27cccc65212581d3c73e2c14c1cd6ee1
      with:
        path: gordon-plugin/gradle.properties
        property: version
        value: ${{ steps.next_version.outputs.next-version }}

    - name: Commit Version Bump
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add gordon-plugin/gradle.properties
        git commit -m "Bump version to ${{ steps.next_version.outputs.next-version }}"
        git push
